# Generated by Django 6.0 on 2026-01-06 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bg_Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Category_product_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bg_Category_product_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Interest_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Bg_Interest_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bg_Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bg_Order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Bg_Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Recent_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bg_Recent_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Bg_Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=150, unique=True)),
                ('user_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Bg_User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bg_Wishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bg_AI_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='intelligence.bg_product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_AI_recommendation',
            },
        ),
    ]
