# Generated by Django 6.0 on 2026-01-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('detail_address', models.CharField(max_length=500)),
                ('is_default', models.IntegerField(default=0)),
                ('recipient_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Bg_Address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Bg_FAQ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('product_status', models.CharField(default='SALE', max_length=20)),
                ('origin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Bg_Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_is_read', models.IntegerField(default=1)),
                ('inquery_is_read', models.IntegerField(default=1)),
                ('order_is_read', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Bg_User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Interest_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.bg_interest_category')),
            ],
            options={
                'db_table': 'Bg_Interest_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(default='PENDING', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_address')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_Order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Order_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
            ],
            options={
                'db_table': 'Bg_Order_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Category_product_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_category', models.ForeignKey(db_column='interest_category_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_interest_category')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
            ],
            options={
                'db_table': 'Bg_Category_product_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Product_Similarity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('similar_product_id', models.IntegerField()),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
            ],
            options={
                'db_table': 'Bg_Product_Similarity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('question_status', models.CharField(default='PENDING', max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_Question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_question')),
            ],
            options={
                'db_table': 'Bg_Answer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Question_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_question')),
            ],
            options={
                'db_table': 'Bg_Question_Image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_Review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Review_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_review')),
            ],
            options={
                'db_table': 'Bg_Review_Image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Recent_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_Recent_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_Cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Alarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.IntegerField(default=0)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_Alarm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_AI_recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_AI_recommendation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bg_address',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user'),
        ),
        migrations.CreateModel(
            name='Bg_User_category_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest_category', models.ForeignKey(db_column='interest_category_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_interest_category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_User_category_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bg_Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_user')),
            ],
            options={
                'db_table': 'Bg_Wishlist',
                'managed': True,
            },
        ),
    ]
