# Generated by Django 6.0 on 2025-12-31 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Bg_Category',
            },
        ),
        migrations.AddField(
            model_name='bg_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Bg_Product_Category_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.bg_product')),
            ],
            options={
                'db_table': 'Bg_Product_Category_Mapping',
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='Bg_Category_product',
        ),
    ]
