# Generated by Django 6.0 on 2026-01-23 02:33

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_ai_recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_alarm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_question_image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_recent_product',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_review_image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_review_image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_user_category_mapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='bg_wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterModelTable(
            name='bg_address',
            table='bg_address',
        ),
        migrations.AlterModelTable(
            name='bg_ai_recommendation',
            table='bg_aI_recommendation',
        ),
        migrations.AlterModelTable(
            name='bg_alarm',
            table='bg_alarm',
        ),
        migrations.AlterModelTable(
            name='bg_answer',
            table='bg_answer',
        ),
        migrations.AlterModelTable(
            name='bg_cart',
            table='bg_cart',
        ),
        migrations.AlterModelTable(
            name='bg_category_product_mapping',
            table='bg_category_product_mapping',
        ),
        migrations.AlterModelTable(
            name='bg_faq',
            table='bg_faq',
        ),
        migrations.AlterModelTable(
            name='bg_interest_category',
            table='bg_interest_category',
        ),
        migrations.AlterModelTable(
            name='bg_order',
            table='bg_order',
        ),
        migrations.AlterModelTable(
            name='bg_order_item',
            table='bg_order_item',
        ),
        migrations.AlterModelTable(
            name='bg_product',
            table='bg_product',
        ),
        migrations.AlterModelTable(
            name='bg_product_similarity',
            table='bg_product_similarity',
        ),
        migrations.AlterModelTable(
            name='bg_question',
            table='bg_question',
        ),
        migrations.AlterModelTable(
            name='bg_question_image',
            table='bg_question_image',
        ),
        migrations.AlterModelTable(
            name='bg_recent_product',
            table='bg_recent_product',
        ),
        migrations.AlterModelTable(
            name='bg_review',
            table='bg_review',
        ),
        migrations.AlterModelTable(
            name='bg_review_image',
            table='bg_review_image',
        ),
        migrations.AlterModelTable(
            name='bg_user',
            table='bg_user',
        ),
        migrations.AlterModelTable(
            name='bg_user_category_mapping',
            table='bg_user_category_mapping',
        ),
        migrations.AlterModelTable(
            name='bg_wishlist',
            table='bg_wishlist',
        ),
    ]
