# Generated by Django 6.0 on 2026-01-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_alter_bg_address_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bg_product',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='bg_ai_recommendation',
            table='bg_ai_recommendation',
        ),
    ]
