# Generated by Django 6.0 on 2026-01-05 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_bg_category_bg_cart_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bg_category',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bg_category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.bg_category'),
        ),
        migrations.AlterField(
            model_name='bgairecommendation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='bg_category',
            table='Bg_Interest_category',
        ),
        migrations.AlterModelTable(
            name='bg_product_category_mapping',
            table='Bg_Category_product_mapping',
        ),
        migrations.AlterModelTable(
            name='bg_user_interest',
            table='Bg_User_category_mapping',
        ),
        migrations.AlterModelTable(
            name='bgairecommendation',
            table='Bg_AI_recommendation',
        ),
    ]
